import type { Invoice } from "./types";

export const SEED_INVOICES: Invoice[] = [
  {
    id: "BK4521",
    createdAt: "2022-03-10",
    paymentDue: "2022-03-11",
    description: "Brand Identity",
    paymentTerms: 1,
    clientName: "Marcus Reid",
    clientEmail: "marcusreid@outlook.com",
    status: "paid",
    senderAddress: { street: "42 Harbour Lane", city: "Manchester", postCode: "M1 4AP", country: "United Kingdom" },
    clientAddress: { street: "22 Elmwood Drive", city: "Norwich", postCode: "NR1 2TH", country: "United Kingdom" },
    items: [{ id: "1", name: "Brand Style Guide", quantity: 1, price: 2100.0, total: 2100.0 }],
    total: 2100.0,
  },
  {
    id: "PL6372",
    createdAt: "2022-04-05",
    paymentDue: "2022-05-05",
    description: "UI/UX Design",
    paymentTerms: 30,
    clientName: "Sofia Mensah",
    clientEmail: "sofia.mensah@webmail.com",
    status: "pending",
    senderAddress: { street: "42 Harbour Lane", city: "Manchester", postCode: "M1 4AP", country: "United Kingdom" },
    clientAddress: { street: "17 Crown Street", city: "Leeds", postCode: "LS1 4DW", country: "United Kingdom" },
    items: [
      { id: "1", name: "Mobile App Screens", quantity: 3, price: 180.0, total: 540.0 },
      { id: "2", name: "Prototype & Handoff", quantity: 1, price: 350.0, total: 350.0 },
    ],
    total: 890.0,
  },
  {
    id: "GH7205",
    createdAt: "2022-05-14",
    paymentDue: "2022-05-21",
    description: "E-Commerce Development",
    paymentTerms: 7,
    clientName: "Daniel Osei",
    clientEmail: "d.osei@techfirm.io",
    status: "paid",
    senderAddress: { street: "42 Harbour Lane", city: "Manchester", postCode: "M1 4AP", country: "United Kingdom" },
    clientAddress: { street: "55 Riverside Close", city: "Bristol", postCode: "BS1 6XP", country: "United Kingdom" },
    items: [{ id: "1", name: "Full Stack Development", quantity: 1, price: 9750.5, total: 9750.5 }],
    total: 9750.5,
  },
  {
    id: "NW3318",
    createdAt: "2022-06-02",
    paymentDue: "2022-06-03",
    description: "Icon Set Design",
    paymentTerms: 1,
    clientName: "Priya Nair",
    clientEmail: "priya.nair@creativemail.com",
    status: "pending",
    senderAddress: { street: "42 Harbour Lane", city: "Manchester", postCode: "M1 4AP", country: "United Kingdom" },
    clientAddress: { street: "9 Victoria Terrace", city: "Edinburgh", postCode: "EH1 2AB", country: "United Kingdom" },
    items: [{ id: "1", name: "Custom Icon Pack (48 icons)", quantity: 1, price: 1450.75, total: 1450.75 }],
    total: 1450.75,
  },
  {
    id: "ZC8830",
    createdAt: "2022-06-20",
    paymentDue: "2022-06-27",
    description: "Marketing Campaign",
    paymentTerms: 7,
    clientName: "Kevin Adler",
    clientEmail: "kevin.adler@adlerco.net",
    status: "pending",
    senderAddress: { street: "42 Harbour Lane", city: "Manchester", postCode: "M1 4AP", country: "United Kingdom" },
    clientAddress: { street: "101 Birch Avenue", city: "Oxford", postCode: "OX2 7HN", country: "United Kingdom" },
    items: [
      { id: "1", name: "Social Media Kit", quantity: 1, price: 980.0, total: 980.0 },
      { id: "2", name: "Campaign Copywriting", quantity: 1, price: 1200.0, total: 1200.0 },
    ],
    total: 2180.0,
  },
  {
    id: "QR5564",
    createdAt: "2022-07-08",
    paymentDue: "2022-07-09",
    description: "Dashboard UI Design",
    paymentTerms: 1,
    clientName: "Claire Fontaine",
    clientEmail: "claire@fontainestudio.fr",
    status: "pending",
    senderAddress: { street: "42 Harbour Lane", city: "Manchester", postCode: "M1 4AP", country: "United Kingdom" },
    clientAddress: { street: "28 Rue de la Paix", city: "Lyon", postCode: "69001", country: "France" },
    items: [
      { id: "1", name: "Analytics Dashboard Design", quantity: 1, price: 4870.0, total: 4870.0 },
    ],
    total: 4870.0,
  },
  {
    id: "MJ1197",
    createdAt: "2022-08-19",
    paymentDue: "2022-09-18",
    description: "Motion Graphics",
    paymentTerms: 30,
    clientName: "Emeka Okafor",
    clientEmail: "emeka@okafordesign.com",
    status: "draft",
    senderAddress: { street: "42 Harbour Lane", city: "Manchester", postCode: "M1 4AP", country: "United Kingdom" },
    clientAddress: { street: "", city: "", postCode: "", country: "" },
    items: [{ id: "1", name: "Intro Animation (30s)", quantity: 1, price: 2250.0, total: 2250.0 }],
    total: 2250.0,
  },
];
